org: imbhavaniprasad
app: aws-serverless-basics
service: aws-serverless-basics
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'

functions:
  handler:
    handler: handler.handler
    events:
      - http:
          path: /
          method: get
          cors: true
